-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 15:15:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EducaView
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EducaView
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EducaView` DEFAULT CHARACTER SET utf8 ;
USE `EducaView` ;

-- -----------------------------------------------------
-- Table `EducaView`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `Nome` VARCHAR(70) NOT NULL,
  `Foto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaView`.`Simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Simulado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `DatadeGeracao` DATETIME NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaView`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Categoria` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` CHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaView`.`Questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Questao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TextoDaQuestao` VARCHAR(2000) NOT NULL,
  `Categoria_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Questão_Categoria1_idx` (`Categoria_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Questão_Categoria1`
    FOREIGN KEY (`Categoria_Id`)
    REFERENCES `EducaView`.`Categoria` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaView`.`Alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Alternativa` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TextoDaAlternativa` VARCHAR(1500) NOT NULL,
  `Correta` TINYINT NOT NULL,
  `Questao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Alternativa_Questão1_idx` (`Questao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Alternativa_Questão1`
    FOREIGN KEY (`Questao_Id`)
    REFERENCES `EducaView`.`Questao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1251;


-- -----------------------------------------------------
-- Table `EducaView`.`Simulado_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Simulado_has_Usuario` (
  `Simulado_Id` INT NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Simulado_Id`, `Usuario_Id`),
  INDEX `fk_Simulado_has_Usuário_Usuário1_idx` (`Usuario_Id` ASC) VISIBLE,
  INDEX `fk_Simulado_has_Usuário_Simulado_idx` (`Simulado_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Simulado_has_Usuário_Simulado`
    FOREIGN KEY (`Simulado_Id`)
    REFERENCES `EducaView`.`Simulado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Simulado_has_Usuário_Usuário1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `EducaView`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaView`.`Questao_has_Simulado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Questao_has_Simulado` (
  `Questao_Id` INT NOT NULL,
  `Simulado_Id` INT NOT NULL,
  PRIMARY KEY (`Questao_Id`, `Simulado_Id`),
  INDEX `fk_Questão_has_Simulado_Simulado1_idx` (`Simulado_Id` ASC) VISIBLE,
  INDEX `fk_Questão_has_Simulado_Questão1_idx` (`Questao_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Questão_has_Simulado_Questão1`
    FOREIGN KEY (`Questao_Id`)
    REFERENCES `EducaView`.`Questao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questão_has_Simulado_Simulado1`
    FOREIGN KEY (`Simulado_Id`)
    REFERENCES `EducaView`.`Simulado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EducaView`.`Questao_has_Simulado_has_Alternativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EducaView`.`Questao_has_Simulado_has_Alternativa` (
  `Questao_has_Simulado_Questao_Id` INT NOT NULL,
  `Questao_has_Simulado_Simulado_Id` INT NOT NULL,
  `Alternativa_Id` INT NOT NULL,
  `Usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Questao_has_Simulado_Questao_Id`, `Questao_has_Simulado_Simulado_Id`, `Alternativa_Id`),
  INDEX `fk_Questão_has_Simulado_has_Alternativa_Alternativa1_idx` (`Alternativa_Id` ASC) VISIBLE,
  INDEX `fk_Questão_has_Simulado_has_Alternativa_Questão_has_Simul_idx` (`Questao_has_Simulado_Questao_Id` ASC, `Questao_has_Simulado_Simulado_Id` ASC) VISIBLE,
  INDEX `fk_Questão_has_Simulado_has_Alternativa_Usuário1_idx` (`Usuario_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Questão_has_Simulado_has_Alternativa_Questão_has_Simulado1`
    FOREIGN KEY (`Questao_has_Simulado_Questao_Id` , `Questao_has_Simulado_Simulado_Id`)
    REFERENCES `EducaView`.`Questao_has_Simulado` (`Questao_Id` , `Simulado_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questão_has_Simulado_has_Alternativa_Alternativa1`
    FOREIGN KEY (`Alternativa_Id`)
    REFERENCES `EducaView`.`Alternativa` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questão_has_Simulado_has_Alternativa_Usuário1`
    FOREIGN KEY (`Usuario_Id`)
    REFERENCES `EducaView`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
